Гришина. Task №3
grishinak/spbu-python-course pull request #2
Opened 2024-10-14 17:23 UTC by grishinak

- [x] Написать генераторное выражение для четырехмерного набора векторов [RGBA](https://en.wikipedia.org/wiki/RGBA_color_model) модели, где прозрачность принимает только чётные значения. Реализуйте функцию, возвращаю `i` элемент этого набора. Каждый цвет может принимать значения от 0 до 255 включительно, прозрачность может принимать значения от 0 до 100 включительно.
- [x] Реализовать функцию-генератор последовательности простых чисел. Обернуть её в декоратор, возвращающий `k`-е простое число (нумерация с единицы).
- [x] Добавить тесты покрывающие реализованную функциональность. Тесты должны использовать либо декоратор pytest.fixture, либо pytest.parametrize.

P.S. 
п.1: четные значения `А` проверкой через `if` в генераторном выражении.
п.3: тесты используют  pytest.parametrize.

2024-10-15 10:59 UTC, Krekep requested changes
Необходимы исправления

2024-10-15 10:59 UTC, Krekep commented on project/prime_generator.py
> +            primes.append(number)
С одной стороны это решение работает быстрее наивного, но с другой стороны оно требует дополнительной (и не константой) памяти.
Суть этого генератора в том, что он может сгенерировать бесконечную последовательность простых чисел, но добавив в него массив, в котором хранятся найденный простые, Вы ограничили размер последовательности.
Перепишите его без использования массива с простыми числами

2024-10-15 10:59 UTC, Krekep commented on project/prime_generator.py
> +        prime_gen = func()
Зачем каждый раз создавать переменную `prime_gen`? С учётом того, что `k` на вход мы по условию подаём в неубывающем порядке, то можно написать более оптимальное решение

2024-10-15 10:59 UTC, Krekep commented on project/prime_generator.py
> +        prime: Union[int, None] = None
Скорее не `Union`, а `Optional`

2024-10-15 19:04 UTC, grishinak commented on project/prime_generator.py
> +            primes.append(number)
Переписала без использования списка

2024-10-15 19:10 UTC, grishinak commented on project/prime_generator.py
> +        prime_gen = func()
Теперь создаю `prime_gen` единожды, в функции-декораторe `get_kth_prime` перед `wrapper`

2024-10-15 19:36 UTC, grishinak commented on project/prime_generator.py
> +        prime: Union[int, None] = None
Изначально имелось ввиду логическое ИЛИ, и учитывая, что Optional[Х] эквивалентно Union[Х, None] (из документации), но в целом да. 
Переписала и без того и без другого.. в текущей реализации `prime` инициализируется значением 0

2024-10-18 16:11 UTC, Krekep approved these changes
Зачтено

2024-10-18 16:11 UTC, Krekep commented on tests/test_prime_generator.py
> +        return prime_number_generator()
Чтобы проверить, что у Вас можно несколько раз вызвать генератор обёрнутый в `get_kth_prime`, это функцию надо было вынести за пределы `test_get_kth_prime`.
Сейчас у Вас нет теста, проверяющего, что можно несколько раз подряд вызвать `get_kth_prime` и ничего не сломается при этом

2024-10-22 19:35 UTC, merged