Гришина. Task#4
grishinak/spbu-python-course pull request #4
Opened 2024-10-22 21:41 UTC by grishinak

# Задача 4. Пул потоков

* **Дедлайн**: 24.10.2024, 23:59
* Полный балл: 10

## Задача

- [x] Реализовать паттерн "пул потоков".
  - [x] Число потоков задаётся константой в классе пула или параметром конструктора.
  - [x] У каждого потока есть два состояния: ожидание задачи, выполнение задачи.
  - [x] Задача --- некая функция проводящая вычисления и возвращающая результат.
  - [x] Добавление задачи осуществляется с помощью метода `enqueue(task)`
  - [x] При добавлении задачи, если в пуле есть ожидающий поток, то он должен приступить к её выполнению. Иначе задача будет ожидать исполнения, пока не освободится какой-нибудь поток.
  - [x] Метод `dispose` должен завершать работу потоков. Уже запущенные задачи не прерываются, но новые задачи не принимаются на исполнение потоками из пула.
  - [x] Ограничения:
    - Разрешено использовать только пакет threading
    - Для каждого базового сценария должен быть написан несложный тест
    - Также должен быть написан тест, проверяющий, что в пуле действительно не менее `n` потоков
  - [x] Допущения:
    - Использование класса для реализации пула потоков необязательно
- [ ] **(Доп., +2 балла)** С помощью `concurrent.futures` реализовать параллельное вычисление суммы полного декартового произведения множества целых чисел

P.S. Использование класса для реализации пула потоков необязательно.- (реализовано с использованием класса)

2024-10-23 08:27 UTC, Krekep requested changes
Всё хорошо, надо только тесты поправить

2024-10-23 08:27 UTC, Krekep commented on tests/threadpool/test_thread_pool.py
> +    assert len(pool.threads) == 5
`len(pool.threads) == 5` на самом деле проверяет, что Вы занесли в массив 5 элементов, а не то, что у Вас в данный момент времени действительно активны 5 потоков в системе. Попробуйте использовать `threading_active_count()` в этом тесте

2024-10-23 08:27 UTC, Krekep commented on tests/threadpool/test_thread_pool.py
> +    assert len(pool.threads) >= n  # check that there are at least n threads in the pool
А как в тредпуле может оказаться больше `n` потоков?

2024-10-23 17:14 UTC, grishinak commented on tests/threadpool/test_thread_pool.py
> +    assert len(pool.threads) >= n  # check that there are at least n threads in the pool
По построению, действительно, никак. Изменила на равенство. 

Но все же добавила 2 вариант с НЕ(менее),который, по всей видимости, избыточный. Формулировка требования к тесту звучит именно так:)

2024-10-23 17:24 UTC, grishinak commented on tests/threadpool/test_thread_pool.py
> +    assert len(pool.threads) == 5
Переписала тест с использованием `threading_active_count()`.

2024-10-24 09:41 UTC, Krekep approved these changes
Зачтено

2024-10-30 08:30 UTC, merged