Гришина. Task#5
grishinak/spbu-python-course pull request #5
Opened 2024-10-31 13:04 UTC by grishinak

# Задача 5. Игра

* Дедлайн: 31.10.2024, 23:59
* Полный балл: 13

## Задача

- [X] Реализовать одну из игр (блекджек) в списке ниже. Вариант определяется как длина Вашего ФИО по модулю 2 плюс 1
  1. [рулетка]
  2. [блэкджек](https://ru.wikipedia.org/wiki/%D0%91%D0%BB%D1%8D%D0%BA%D0%B4%D0%B6%D0%B5%D0%BA)
-  выбор варианта
  - len(Гришина Ксения) = 7 + 6  = 13
  - 13 % 2 = 1
  - 1 + 1 = 2 -> вариант 2 
-------------------
  - Требования:
    - [X] Должно быть как минимум три различных стратегии игры ботов
    - [x] Должны быть методы, показывающие текущее состояние игры
    - [x] На каждую сущность должен быть свой класс
  - Ограничения:
    - Игра ведётся либо до победы одного/нескольких участников, либо до заданного количества шагов
  - Допущения:
    - Реализовывать Игрока необязательно. Достаточно того, что в игре будут участвовать только боты. (Не реализовывала)
    - Графический интерфейс необязателен. Информацию достаточно выводить в консоль. (Без графического интерфейса. Вывожу в консоль.)
  - Проверка:
    - Будет проверяться декомпозиция на классы
    - Тесты должны отображать
      - Что состояние игры меняется с течением времени
      - Работоспособность методов влияющих на состояние игры
      - Может быть что-то ещё, тестов много не бывает
    - Надо добавить пример работы игры с выводом информации о состоянии в каждом раунде. Для примеров лучше создать отдельную папку examples
- [x] (Доп., +5 балла) Для реализованной игры построить [UML диаграмму классов](https://en.wikipedia.org/wiki/Class_diagram)
- [ ] (Доп., +5 балла) С помощью метаклассов добавить стратегию бота и поменять правила игры (к примеру, количество полей или условия победы)

2024-11-01 16:41 UTC, Krekep requested changes
Необходимы исправления

2024-11-01 16:41 UTC, Krekep commented on project/blackjack_game/src/card.py
> +        :param suit: The suit of the card (e.g., "♠️", "♥️", "♦️", "♣️").
Использование [магических констант](https://en.wikipedia.org/wiki/Magic_number_(programming)) это антипаттерн, создайте перечисление для хранения значений и мастей.
Для красивого вывода можно написать функцию, которая отображает значение перечисления в символ

2024-11-01 16:41 UTC, Krekep commented on project/blackjack_game/src/main.py
Это файл, демонстрирующий сценарии использования реализованной игры. Собственно, он дублирует файл `examples/main.py`, поэтому его можно удалить

2024-11-01 16:41 UTC, Krekep commented on project/blackjack_game/src/player.py
> +class Bot(Player):
У Вас по факту одна и та же стратегия, добавьте более сложную стратегию, которая зависит, к примеру, от истории ставок/выигрышей/проигрышей

2024-11-01 16:41 UTC, Krekep commented on project/blackjack_game/src/player.py
> +                print(f"{self.name} draws 🎴 {self.hand[-1]}.")
Вместо `elif` следует использовать несколько дочерних классов

2024-11-01 16:41 UTC, Krekep commented on project/blackjack_game/src/game.py
> +            self.dealer.add_card(self.deck.draw())
Здесь, наверное стоит использовать `self.dealer.make_move(self.deck)`

2024-11-01 16:41 UTC, Krekep commented on project/blackjack_game/UML/uml.png
1. На диаграмме все поля отмечены приватными, но в коде это не отражено
2. Также не все методы (к примеру, `play_round`) должны быть публичными, проверьте, что Ваш код соблюдает принцип инкапсуляции
3. Между колодой, игроком и картами связь должна быть агрегация или композиция, не ассоциация.
4. Игра содержит в себе набор игроков, дилера и колоду, поэтому связь должна быть композицией

2024-11-10 14:50 UTC, grishinak commented on project/blackjack_game/src/main.py
Удалила. Не знала просто где его следовало оставлять.

2024-11-10 14:53 UTC, grishinak commented on project/blackjack_game/src/player.py
> +class Bot(Player):
Добавила стратегию `AdaptiveStrategy(Strategy)` в `strategy.py`, которая зависит от результатов и ставок на предыдущем раунде.

2024-11-10 14:55 UTC, grishinak commented on project/blackjack_game/src/player.py
> +                print(f"{self.name} draws 🎴 {self.hand[-1]}.")
Завела классы стратегий и вынесла их реализацию в модуле `strategy.py`, которые после используют боты.

2024-11-10 14:56 UTC, grishinak commented on project/blackjack_game/src/game.py
> +            self.dealer.add_card(self.deck.draw())
Исправила.

2024-11-10 14:59 UTC, grishinak commented on project/blackjack_game/UML/uml.png
Изменила диаграмму и добавила на нее новые классы, появившиеся в ходе исправлений.

2024-11-10 14:59 UTC, grishinak commented on project/blackjack_game/src/card.py
> +        :param suit: The suit of the card (e.g., "♠️", "♥️", "♦️", "♣️").
Создала перечисление для мастей.

2024-11-10 15:01 UTC, grishinak commented
Внесла требуемые поправки.

2024-11-15 09:22 UTC, Krekep approved these changes
Зачтено

2024-11-15 09:22 UTC, Krekep commented on project/blackjack_game/src/card.py
> +            return 10
Кстати можно было создать перечисление/словарь и для значений карт

2024-11-18 19:49 UTC, merged